/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiJunoAskRouteImport } from './routes/api/juno/ask'
import { Route as ApiJunoSpeakRouteImport } from './routes/api/juno/speak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJunoAskRoute = ApiJunoAskRouteImport.update({
  id: '/api/juno/ask',
  path: '/api/juno/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJunoSpeakRoute = ApiJunoSpeakRouteImport.update({
  id: '/api/juno/speak',
  path: '/api/juno/speak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/juno/ask': typeof ApiJunoAskRoute
  '/api/juno/speak': typeof ApiJunoSpeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/juno/ask': typeof ApiJunoAskRoute
  '/api/juno/speak': typeof ApiJunoSpeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/juno/ask': typeof ApiJunoAskRoute
  '/api/juno/speak': typeof ApiJunoSpeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/juno/ask' | '/api/juno/speak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/juno/ask' | '/api/juno/speak'
  id: '__root__' | '/' | '/api/juno/ask' | '/api/juno/speak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiJunoAskRoute: typeof ApiJunoAskRoute
  ApiJunoSpeakRoute: typeof ApiJunoSpeakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/juno/ask': {
      id: '/api/juno/ask'
      path: '/api/juno/ask'
      fullPath: '/api/juno/ask'
      preLoaderRoute: typeof ApiJunoAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/juno/speak': {
      id: '/api/juno/speak'
      path: '/api/juno/speak'
      fullPath: '/api/juno/speak'
      preLoaderRoute: typeof ApiJunoSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiJunoAskRoute: ApiJunoAskRoute,
  ApiJunoSpeakRoute: ApiJunoSpeakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
